[package]
name = "thalos_planet_editor"
version.workspace = true
edition.workspace = true

[dependencies]
thalos_physics_canonical = { path = "../physics_canonical" }
thalos_input = { path = "../input" }
thalos_terrain = { path = "../terrain" }
thalos_planet_rendering = { path = "../planet_rendering" }
thalos_celestial = { path = "../celestial" }
bevy = { version = "0.18", features = ["wayland", "jpeg"] }
bevy_egui = "0.39"
