use glam::Vec3;
use thalos_terrain_gen::*;

fn mira_composition() -> Composition {
    Composition::new(0.85, 0.10, 0.0, 0.05, 0.0)
}

fn mira_megabasin() -> Megabasin {
    Megabasin {
        basins: vec![
            BasinDef {
                center_dir: Vec3::new(0.25, 0.35, 0.90).normalize(),
                radius_m: 320_000.0,
                depth_m: 7_500.0,
                ring_count: 4,
                seed: None,
            },
            BasinDef {
                center_dir: Vec3::new(-0.35, -0.30, 0.85).normalize(),
                radius_m: 220_000.0,
                depth_m: 5_200.0,
                ring_count: 3,
                seed: None,
            },
        ],
        hemispheric_lowering_m: 2_000.0,
    }
}

fn mira_pipeline() -> Pipeline {
    Pipeline::new(vec![
        Box::new(Differentiate),
        Box::new(mira_megabasin()),
        Box::new(Cratering {
            total_count: 10_000,
            sfd_slope: 1.8,
            sfd_slope_small: Some(3.3),
            sfd_break_radius_m: Some(1_000.0),
            min_radius_m: 1_500.0,
            max_radius_m: 250_000.0,
            age_bias: 2.0,
            cubemap_bake_threshold_m: 10_000.0,
            secondary_parent_radius_m: 50_000.0,
            secondaries_per_parent: 20,
            saturation_fraction: 0.05,
            chain_count: 3,
            chain_segment_count: 10,
            forced_young_count: 16,
        }),
        Box::new(MareFlood {
            target_count: 5,
            additional_crater_count: 0,
            fill_fraction: 0.7,
            near_side_bias: 0.9,
            boundary_noise_amplitude_m: 700.0,
            boundary_noise_freq: 4.0,
            episode_count: 3,
            wrinkle_ridges: true,
            procellarum: None,
        }),
        Box::new(Regolith {
            amplitude_m: 3.0,
            characteristic_wavelength_m: 50.0,
            crater_density_multiplier: 1.0,
            bake_d_min_m: 600.0,
            bake_scale: 1.0,
            density_modulation: 0.25,
            density_wavelength_m: 250_000.0,
        }),
        Box::new(SpaceWeather {
            highland_mature_albedo: Some(0.10),
            highland_fresh_albedo: Some(0.18),
            mare_mature_albedo: 0.065,
            mare_fresh_albedo: 0.09,
            mare_tint: [1.0, 1.0, 1.0],
            young_crater_age_threshold: 0.5,
            ray_age_threshold: 0.1,
            ray_extent_radii: 7.0,
            ray_count_per_crater: 8,
            ray_half_width: 0.06,
        }),
    ])
}

fn mira_builder(resolution: u32) -> BodyBuilder {
    BodyBuilder::new(
        869_000.0,
        42,
        mira_composition(),
        resolution,
        4.5,
        Some(Vec3::Z),
        0.0,
    )
}

#[test]
fn full_mira_pipeline_produces_valid_body() {
    let mut builder = mira_builder(0);
    assert_eq!(builder.cubemap_resolution, 1024);

    let pipeline = mira_pipeline();
    assert_eq!(pipeline.stage_count(), 6);

    pipeline.run(&mut builder);

    // Materials palette set by Differentiate
    assert_eq!(builder.materials.len(), 4);

    // Craters generated by Cratering (some may be removed by MareFlood)
    assert!(!builder.craters.is_empty());
    assert!(builder.craters.len() <= 100_000);

    // Detail params configured by Regolith
    assert!(builder.detail_params.d_min_m > 0.0);

    let body = builder.build();

    // Basic sanity
    assert_eq!(body.radius_m, 869_000.0);
    assert!(body.height_range > 0.0);
    assert_eq!(body.materials.len(), 4);
}

#[test]
fn mira_has_height_variation() {
    let mut builder = mira_builder(64);
    mira_pipeline().run(&mut builder);

    // The height accumulator should have significant variation from basins + craters.
    let mut min_h = f32::MAX;
    let mut max_h = f32::MIN;
    for face in CubemapFace::ALL {
        for val in builder.height_contributions.height.face_data(face) {
            min_h = min_h.min(*val);
            max_h = max_h.max(*val);
        }
    }
    let range = max_h - min_h;
    // With ~7km megabasins, we expect at least several km of relief.
    assert!(range > 3_000.0, "height range too small: {range}");
    assert!(
        min_h < -1_000.0,
        "no significant depressions: min_h = {min_h}"
    );
}

#[test]
fn near_side_has_mare() {
    let mut builder = mira_builder(64);
    mira_pipeline().run(&mut builder);

    // Count mare-flagged texels on the near side (+Z) vs far side (-Z).
    let res = builder.cubemap_resolution;
    let mut near_mare = 0u32;
    let mut far_mare = 0u32;

    for face in CubemapFace::ALL {
        for y in 0..res {
            for x in 0..res {
                let u = (x as f32 + 0.5) / res as f32;
                let v = (y as f32 + 0.5) / res as f32;
                let dir = thalos_terrain_gen::cubemap::face_uv_to_dir(face, u, v);
                // Inspect the material cubemap directly — encoding-
                // independent and the source of truth for "is this cell
                // mare". The previous absolute-albedo threshold (0.085)
                // was coupled to the SpaceWeather output range and broke
                // when SpaceWeather started re-encoding for the new
                // chromatic-tint shader convention.
                let is_mare = builder.material_cubemap.get(face, x, y)
                    == thalos_terrain_gen::stages::MAT_MARE as u8;
                if is_mare {
                    if dir.z > 0.0 {
                        near_mare += 1;
                    } else {
                        far_mare += 1;
                    }
                }
            }
        }
    }

    // Near side should have significantly more mare than far side.
    assert!(
        near_mare > far_mare * 2,
        "near/far mare asymmetry too weak: near={near_mare}, far={far_mare}"
    );
}

#[test]
fn deterministic_across_runs() {
    let run = || {
        let mut builder = mira_builder(64);
        mira_pipeline().run(&mut builder);
        // Sample a few height values
        let h1 = builder
            .height_contributions
            .height
            .get(CubemapFace::PosZ, 32, 32);
        let h2 = builder
            .height_contributions
            .height
            .get(CubemapFace::NegZ, 16, 16);
        let a1 = builder
            .albedo_contributions
            .albedo
            .get(CubemapFace::PosX, 10, 10);
        (h1, h2, a1)
    };

    let (h1a, h2a, a1a) = run();
    let (h1b, h2b, a1b) = run();

    assert_eq!(h1a, h1b);
    assert_eq!(h2a, h2b);
    assert_eq!(a1a, a1b);
}
