//! The [`TileProvider`] trait — the seam between the renderer and the source
//! of tile data.
//!
//! A [`TileAtlas`](crate::terrain_data::tile_atlas::TileAtlas) holds a single
//! `Box<dyn TileProvider>` and calls [`TileProvider::request_tile`] whenever a
//! tile becomes resident. The provider returns a [`Task`] that resolves to the
//! base data for every attachment of that tile, in the same order as the
//! supplied [`AttachmentConfig`] slice. Mipmaps and uploads are handled
//! downstream.
//!
//! Two impls live in this crate:
//!
//! - [`DiskTileProvider`] reads tiles produced by the offline preprocess
//!   pipeline. It is the default and matches the previous tile-loading
//!   behaviour exactly.
//! - Custom impls can synthesize tile data at runtime — see
//!   [`TileCoordinate::pixel_coordinate`](crate::math::TileCoordinate::pixel_coordinate)
//!   for the canonical pixel→position mapping that keeps tile borders aligned
//!   with neighbours.
//!
//! Tile latency is tolerated by the renderer via parent-LOD fallback. Failed
//! requests leave the tile in a perpetual loading state — providers are
//! expected to surface real errors only for unrecoverable situations.

use crate::{
    math::{TerrainModel, TileCoordinate},
    terrain_data::{tile_atlas::STORE_PNG, AttachmentConfig, AttachmentData, AttachmentFormat},
};
use anyhow::Result;
use bevy::tasks::{AsyncComputeTaskPool, Task};
use image::ImageReader;
use std::fs;

/// Source of tile attachment data for a
/// [`TileAtlas`](crate::terrain_data::tile_atlas::TileAtlas).
///
/// Implementations are held behind `Box<dyn TileProvider>`, so different
/// terrains in the same world can use different providers (disk-loaded,
/// procedurally synthesized, test stubs, etc.).
///
/// # Border alignment
///
/// Each tile texture has a border that overlaps adjacent tiles. For seamless
/// filtering the value at a shared texel must be **bit-identical** between
/// the two tiles that contain it. Providers must therefore evaluate their
/// data source as a pure function of position: same input → same output,
/// regardless of tile evaluation order. Computing texel positions via
/// [`TileCoordinate::pixel_coordinate`](crate::math::TileCoordinate::pixel_coordinate)
/// — which is the same mapping the renderer samples with — is the easiest
/// way to satisfy this.
pub trait TileProvider: Send + Sync {
    /// Produce the base attachment data for `coord`.
    ///
    /// The returned task must resolve to one [`AttachmentData`] per entry in
    /// `attachments`, in the same order. Each `AttachmentData` must contain
    /// `texture_size * texture_size` texels in the layout described by
    /// [`AttachmentFormat`](crate::terrain_data::AttachmentFormat) — only the
    /// base mip; downsampled mips are generated by the atlas.
    fn request_tile(
        &self,
        coord: TileCoordinate,
        model: &TerrainModel,
        attachments: &[AttachmentConfig],
    ) -> Task<Result<Vec<AttachmentData>>>;

    /// Returns `true` if the provider can synthesise data for any valid
    /// [`TileCoordinate`] — i.e. it does not depend on a pre-existing tile set.
    ///
    /// Disk-backed providers leave this `false` (the default): the runtime
    /// loader then gates tile requests on the `existing_tiles` set populated
    /// from `assets/{path}/config.tc`, so we never request tiles that have no
    /// file on disk. Synthesised providers override this to `true` so newly
    /// requested coordinates are loaded on demand without preprocessing.
    fn supports_all_tiles(&self) -> bool {
        false
    }
}

/// [`TileProvider`] backed by tiles produced by the offline preprocess
/// pipeline.
///
/// Tiles are read from `assets/{terrain_path}/data/{attachment_name}/{coord}.{ext}`,
/// where the extension is `bin` (raw bytes) or `png` depending on the build's
/// `STORE_PNG` constant.
pub struct DiskTileProvider {
    terrain_path: String,
}

impl DiskTileProvider {
    pub fn new(terrain_path: impl Into<String>) -> Self {
        Self { terrain_path: terrain_path.into() }
    }
}

impl TileProvider for DiskTileProvider {
    fn request_tile(
        &self,
        coord: TileCoordinate,
        _model: &TerrainModel,
        attachments: &[AttachmentConfig],
    ) -> Task<Result<Vec<AttachmentData>>> {
        let attachment_paths: Vec<(String, AttachmentFormat)> = attachments
            .iter()
            .map(|a| {
                (
                    format!("assets/{}/data/{}", self.terrain_path, a.name),
                    a.format,
                )
            })
            .collect();

        AsyncComputeTaskPool::get().spawn(async move {
            let mut datas = Vec::with_capacity(attachment_paths.len());

            for (base_path, format) in attachment_paths {
                let data = if STORE_PNG {
                    let path = coord.path(&base_path, "png");
                    let mut reader = ImageReader::open(path)?;
                    reader.no_limits();
                    let image = reader.decode().unwrap();
                    AttachmentData::from_bytes(image.as_bytes(), format)
                } else {
                    let path = coord.path(&base_path, "bin");
                    let bytes = fs::read(path)?;
                    AttachmentData::from_bytes(&bytes, format)
                };

                datas.push(data);
            }

            Ok(datas)
        })
    }
}
