<#
    Set up a high-speed Thalos build environment on native Windows.
    Verifies rust-lld, installs sccache, sets sccache env, and (when elevated)
    offers Windows Defender exclusions for the build dirs.

    Full rationale + the agent workflow: docs/build_speed.md

    Usage (from the repo root, PowerShell):
        scripts\setup-build-env.ps1
        scripts\setup-build-env.ps1 -Force     # overwrite existing .cargo\config.toml (backs it up)
#>
param([switch]$Force)

$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path -Parent $PSScriptRoot
$cfg = Join-Path $repoRoot '.cargo\config.toml'

function Have($name) { $null -ne (Get-Command $name -ErrorAction SilentlyContinue) }

Write-Host "==> Platform: windows (native, msvc)"
if (-not (Have 'cargo')) { throw "cargo not found. Install rustup first: https://rustup.rs" }
Write-Host "==> rustc: $(rustc --version)"

# --- rust-lld (fast linker) --------------------------------------------------
$tc = (rustc -vV | Select-String 'host:').ToString().Split(':')[1].Trim()
$sysroot = (rustc --print sysroot).Trim()
$lld = Join-Path $sysroot "lib\rustlib\$tc\bin\rust-lld.exe"
if (Test-Path $lld) {
    Write-Host "==> rust-lld: $lld"
} else {
    Write-Warning "rust-lld.exe not found at $lld"
    Write-Host   "   Install the LLVM tools:  rustup component add llvm-tools"
}

# --- sccache -----------------------------------------------------------------
if (Have 'sccache') {
    Write-Host "==> sccache present: $(sccache --version)"
} else {
    Write-Host "==> Installing sccache"
    if     (Have 'scoop')  { scoop install sccache }
    elseif (Have 'winget') { winget install --id Mozilla.sccache --accept-source-agreements --accept-package-agreements }
    elseif (Have 'cargo-binstall') { cargo binstall -y sccache }
    else   { Write-Host "   (building from source — slow, one time)"; cargo install sccache --locked }
}

# --- sccache env (user-scoped; harmless, only used when RUSTC_WRAPPER is set) -
$sccDir = Join-Path $env:LOCALAPPDATA 'Mozilla\sccache'
[Environment]::SetEnvironmentVariable('SCCACHE_DIR', $sccDir, 'User')
[Environment]::SetEnvironmentVariable('SCCACHE_CACHE_SIZE', '50G', 'User')
Write-Host "==> SCCACHE_DIR=$sccDir  SCCACHE_CACHE_SIZE=50G (user env)"
Write-Host "   Turn sccache ON for a shell (clean builds / worktrees):  . scripts\sccache-on.ps1"

# --- write local .cargo\config.toml if absent --------------------------------
New-Item -ItemType Directory -Force -Path (Split-Path $cfg) | Out-Null
if ((Test-Path $cfg) -and -not $Force) {
    Write-Host "==> .cargo\config.toml already exists — leaving it (use -Force to overwrite)."
} else {
    if (Test-Path $cfg) { Copy-Item $cfg "$cfg.bak"; Write-Host "   (backed up existing config to $cfg.bak)" }
    $lldToml = ($lld -replace '\\','/')
@"
# Generated by scripts\setup-build-env.ps1 (Windows). Local, gitignored.
# See docs/build_speed.md.

[env]
CARGO_INCREMENTAL = "1"

[profile.dev]
incremental = true
debug = "line-tables-only"

[profile.dev.package."*"]
debug = "line-tables-only"

[target.x86_64-pc-windows-msvc]
linker = "$lldToml"

[alias]
check-game = "check -p thalos_game"
"@ | Set-Content -Encoding UTF8 $cfg
    Write-Host "==> Wrote $cfg"
}

# --- Windows Defender exclusions (elevated only) -----------------------------
$elevated = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()
            ).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
if ($elevated) {
    Write-Host "==> Adding Defender exclusions for build dirs (big Windows win)"
    foreach ($p in @((Join-Path $repoRoot 'target'), (Join-Path $env:USERPROFILE '.cargo'),
                     (Join-Path $env:USERPROFILE '.rustup'), $sccDir)) {
        try { Add-MpPreference -ExclusionPath $p; Write-Host "   excluded $p" } catch { Write-Warning "   $p : $_" }
    }
} else {
    Write-Host "==> Not elevated: skipping Defender exclusions."
    Write-Host "   For a 20-40% Windows build win, run an elevated PowerShell and see docs/build_speed.md 3.8."
}

Write-Host ""
Write-Host "Next:  cargo check-game ; just screenshot hub   (see docs/build_speed.md)"
