<#
    Set up a high-speed Thalos build environment on native Windows.
    Verifies rust-lld, installs sccache, sets sccache env, and (when elevated)
    offers Windows Defender exclusions for the build dirs.

    Full rationale + the agent workflow: docs/build_speed.md

    Usage (from the repo root, PowerShell):
        scripts\setup-build-env.ps1
        scripts\setup-build-env.ps1 -Force     # overwrite existing .cargo\config.toml (backs it up)
        scripts\setup-build-env.ps1 -AgentSlots 4
#>
param(
    [switch]$Force,
    [ValidateRange(1, 64)]
    [int]$AgentSlots = 2
)

$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path -Parent $PSScriptRoot
$cfg = Join-Path $repoRoot '.cargo\config.toml'
$logicalCpus = [Environment]::ProcessorCount
$cargoJobs = [Math]::Max(1, [Math]::Floor($logicalCpus / $AgentSlots))
$worktreeRoots = @(
    git -C $repoRoot worktree list --porcelain |
        Where-Object { $_ -like 'worktree *' } |
        ForEach-Object { $_.Substring('worktree '.Length) }
)
if ($worktreeRoots.Count -eq 0) { $worktreeRoots = @($repoRoot) }
$sccBaseDirs = [string]::Join(';', $worktreeRoots)

function Have($name) { $null -ne (Get-Command $name -ErrorAction SilentlyContinue) }

Write-Host "==> Platform: windows (native, msvc)"
if (-not (Have 'cargo')) { throw "cargo not found. Install rustup first: https://rustup.rs" }
Write-Host "==> rustc: $(rustc --version)"

# --- rust-lld (fast linker) --------------------------------------------------
$tc = (rustc -vV | Select-String 'host:').ToString().Split(':')[1].Trim()
$sysroot = (rustc --print sysroot).Trim()
$lld = Join-Path $sysroot "lib\rustlib\$tc\bin\rust-lld.exe"
if (Test-Path $lld) {
    Write-Host "==> rust-lld: $lld"
} else {
    Write-Warning "rust-lld.exe not found at $lld"
    Write-Host   "   Install the LLVM tools:  rustup component add llvm-tools"
}

# --- sccache -----------------------------------------------------------------
$env:Path = @(
    [Environment]::GetEnvironmentVariable('Path', 'Machine'),
    [Environment]::GetEnvironmentVariable('Path', 'User')
) -join ';'
if (Have 'sccache') {
    Write-Host "==> sccache present: $(sccache --version)"
} else {
    Write-Host "==> Installing sccache"
    if     (Have 'scoop')  { scoop install sccache }
    elseif (Have 'winget') { winget install --id Mozilla.sccache --accept-source-agreements --accept-package-agreements }
    elseif (Have 'cargo-binstall') { cargo binstall -y sccache }
    else   { Write-Host "   (building from source — slow, one time)"; cargo install sccache --locked }
}
$env:Path = @(
    [Environment]::GetEnvironmentVariable('Path', 'Machine'),
    [Environment]::GetEnvironmentVariable('Path', 'User')
) -join ';'
if (-not (Have 'sccache')) {
    throw 'sccache was installed but is not discoverable after refreshing PATH'
}
$sccacheExe = (Get-Command 'sccache').Source
Write-Host "==> sccache executable: $sccacheExe"

# --- sccache env -------------------------------------------------------------
$sccDir = Join-Path $env:LOCALAPPDATA 'Mozilla\sccache'
[Environment]::SetEnvironmentVariable('SCCACHE_DIR', $sccDir, 'User')
[Environment]::SetEnvironmentVariable('SCCACHE_CACHE_SIZE', '50G', 'User')
[Environment]::SetEnvironmentVariable('SCCACHE_BASEDIRS', $sccBaseDirs, 'User')
Write-Host "==> SCCACHE_DIR=$sccDir  SCCACHE_CACHE_SIZE=50G (user env)"
Write-Host "==> SCCACHE_BASEDIRS=$sccBaseDirs"
Write-Host "   sccache wraps normal builds; parallel mode additionally disables incremental."

# --- write local .cargo\config.toml if absent --------------------------------
New-Item -ItemType Directory -Force -Path (Split-Path $cfg) | Out-Null
if ((Test-Path $cfg) -and -not $Force) {
    Write-Host "==> .cargo\config.toml already exists — leaving it (use -Force to overwrite)."
} else {
    if (Test-Path $cfg) { Copy-Item $cfg "$cfg.bak"; Write-Host "   (backed up existing config to $cfg.bak)" }
    $lldToml = ($lld -replace '\\','/')
    $sccacheToml = ($sccacheExe -replace '\\','/')
    $sccDirToml = ($sccDir -replace '\\','/')
    $sccBaseToml = ($sccBaseDirs -replace '\\','/')
@"
# Generated by scripts\setup-build-env.ps1 (Windows). Local, gitignored.
# See docs/build_speed.md.

[env]
SCCACHE_DIR = "$sccDirToml"
SCCACHE_CACHE_SIZE = "50G"
SCCACHE_BASEDIRS = "$sccBaseToml"

[build]
jobs = $cargoJobs # $logicalCpus logical CPUs / $AgentSlots expected concurrent agents
rustc-wrapper = "$sccacheToml"

[target.x86_64-pc-windows-msvc]
linker = "$lldToml"
"@ | Set-Content -Encoding UTF8 $cfg
    Write-Host "==> Wrote $cfg"
}

# --- Windows Defender exclusions (elevated only) -----------------------------
$elevated = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()
            ).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
if ($elevated) {
    Write-Host "==> Adding Defender exclusions for build dirs (big Windows win)"
    foreach ($p in @((Join-Path $repoRoot 'target'), (Join-Path $env:USERPROFILE '.cargo'),
                     (Join-Path $env:USERPROFILE '.rustup'), $sccDir)) {
        try { Add-MpPreference -ExclusionPath $p; Write-Host "   excluded $p" } catch { Write-Warning "   $p : $_" }
    }
} else {
    Write-Host "==> Not elevated: skipping Defender exclusions."
    Write-Host "   For a 20-40% Windows build win, run an elevated PowerShell and see docs/build_speed.md 3.8."
}

Write-Host ""
Write-Host "Next:  just check ; just screenshot hub   (see docs/build_speed.md)"
Write-Host "Parallel worktree shell:  . scripts\sccache-on.ps1"
