#!/usr/bin/env bash
# Set up a high-speed Thalos build environment on Linux, WSL2, or macOS.
# Installs a fast linker (mold on Linux/WSL) + sccache, then writes the local,
# gitignored .cargo/config.toml appropriate to this platform.
#
# Full rationale + the agent workflow: docs/build_speed.md
#
# Usage:
#   scripts/setup-build-env.sh            # install tools + write config if absent
#   scripts/setup-build-env.sh --force    # overwrite an existing .cargo/config.toml (backs it up)
set -euo pipefail

FORCE=0
[[ "${1:-}" == "--force" ]] && FORCE=1

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cfg="$repo_root/.cargo/config.toml"

# --- platform detection ------------------------------------------------------
os="$(uname -s)"
is_wsl=0
if [[ "$os" == "Linux" ]] && grep -qiE 'microsoft|wsl' /proc/version 2>/dev/null; then
  is_wsl=1
fi
case "$os" in
  Linux)  platform=$([[ $is_wsl == 1 ]] && echo "wsl" || echo "linux") ;;
  Darwin) platform="macos" ;;
  *) echo "Unsupported OS '$os' — use scripts/setup-build-env.ps1 on Windows." >&2; exit 1 ;;
esac
echo "==> Platform: $platform"

have() { command -v "$1" >/dev/null 2>&1; }

# --- package-manager helpers -------------------------------------------------
pkg_install() {
  # pkg_install <linux-pkgs...> ; on macOS falls through to brew with same names
  if [[ "$platform" == "macos" ]]; then
    have brew && brew install "$@" || echo "  (brew missing — install $* manually)"
    return
  fi
  if have apt-get;  then sudo apt-get update -y && sudo apt-get install -y "$@"; return; fi
  if have dnf;      then sudo dnf install -y "$@"; return; fi
  if have pacman;   then sudo pacman -S --noconfirm "$@"; return; fi
  if have zypper;   then sudo zypper install -y "$@"; return; fi
  echo "  (no known package manager — install $* manually)"
}

# --- rust toolchain sanity ---------------------------------------------------
if ! have cargo; then
  echo "!! cargo not found. Install rustup first: https://rustup.rs" >&2
  exit 1
fi
echo "==> rustc: $(rustc --version)"

# --- fast linker -------------------------------------------------------------
if [[ "$platform" == "linux" || "$platform" == "wsl" ]]; then
  if ! have mold;  then echo "==> Installing mold";  pkg_install mold;  else echo "==> mold present";  fi
  if ! have clang; then echo "==> Installing clang"; pkg_install clang; else echo "==> clang present"; fi
else
  echo "==> macOS: using the default (fast) Apple linker — nothing to install."
fi

# --- headless Vulkan (screenshot tool) --------------------------------------
if [[ "$platform" == "linux" || "$platform" == "wsl" ]]; then
  if ! have vulkaninfo; then
    echo "==> Installing Mesa Vulkan (real-GPU driver preferred; lavapipe is the software fallback)"
    pkg_install mesa-vulkan-drivers vulkan-tools || true
  fi
fi

# --- sccache -----------------------------------------------------------------
if have sccache; then
  echo "==> sccache present: $(sccache --version)"
else
  echo "==> Installing sccache"
  if   have cargo-binstall; then cargo binstall -y sccache
  elif [[ "$platform" == "macos" ]] && have brew; then brew install sccache
  elif have apt-get && apt-cache show sccache >/dev/null 2>&1; then pkg_install sccache
  else echo "   (building from source — slow, one time)"; cargo install sccache --locked; fi
fi

# --- write local .cargo/config.toml -----------------------------------------
mkdir -p "$repo_root/.cargo"
if [[ -f "$cfg" && $FORCE -eq 0 ]]; then
  echo "==> .cargo/config.toml already exists — leaving it (pass --force to overwrite)."
else
  [[ -f "$cfg" ]] && cp "$cfg" "$cfg.bak.$(date +%s 2>/dev/null || echo prev)" && echo "   (backed up existing config)"
  {
    echo "# Generated by scripts/setup-build-env.sh for platform: $platform"
    echo "# Local, gitignored, per-machine. See docs/build_speed.md."
    echo ""
    echo "[env]"
    echo "CARGO_INCREMENTAL = \"1\"   # Iterate regime; set 0 in-shell for sccache (scripts/sccache-on.sh)"
    echo ""
    echo "[profile.dev]"
    echo "incremental = true"
    echo "debug = \"line-tables-only\""
    echo ""
    echo "[profile.dev.package.\"*\"]"
    echo "debug = \"line-tables-only\""
    echo ""
    if [[ "$platform" == "linux" || "$platform" == "wsl" ]]; then
      echo "[target.x86_64-unknown-linux-gnu]"
      echo "linker = \"clang\""
      echo "rustflags = [\"-C\", \"link-arg=-fuse-ld=mold\"]"
      echo ""
    fi
    echo "[alias]"
    echo "check-game = \"check -p thalos_game\""
  } > "$cfg"
  echo "==> Wrote $cfg"
fi

# --- verify ------------------------------------------------------------------
echo ""
echo "==> Done. Quick checks:"
[[ "$platform" != "macos" ]] && { have mold && echo "   mold:    $(mold --version | head -1)"; }
have sccache && echo "   sccache: $(sccache --version)"
echo ""
echo "Next:"
echo "  * Iterate loop (one machine):   cargo check-game ; just screenshot hub"
echo "  * Parallel/cloud (sccache on):  source scripts/sccache-on.sh   # then cargo/just"
echo "  * Verify sccache pays off:      sccache --show-stats"
echo "  * See docs/build_speed.md for the full per-environment agent workflow."
